theme: jekyll-theme-minimal
title: Tensors In Rain
author: Julie Butler Hartley
description: Programming and Physics, One Drop At A Time
comments: true
provider: "facebook"
baseurl: ""
url: http://tensorsinrain.github.io
logo: "TiR_Small.png"
