theme: jekyll-theme-minimal
title: Tensors In Rain
description: Machine Learning, One Drop At A Time
comments: true
provider: "facebook"
baseurl: ""
url: http://tensorsinrain.github.io
avatar: "TiR.png"
